apiVersion: v1
kind: ConfigMap
metadata:
  name: cometchat-back-configmap
data:
  DATABASE_URL: ""
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  FRONT_URL: ""
  AUTH0_DOMAIN: ""
  AUTH0_CLIENT_ID: ""
  AUTH0_AUDIENCE: ""
  AUTH0_CLIENT_SECRET: ""
  AUTH0_M_TO_M_AUDIENCE: ""
  AUTH0_M_TO_M_CLIENT_ID: ""
  AUTH0_M_TO_M_CLIENT_SECRET: ""
  PORT: "3002"
